### PR TITLE
Added ls ~ as specific shortcut

### PR DESCRIPTION
**Pull request by winkleink**
Added suggestion for ls ~ as a specific shortcut to return to users home directory.

### CODE REVIEW

**Comment by SteveAmor** [comment]
I may be wrong but as far as I can see, ```ls ~``` will list the subdirectory /home/pi/
However, ```cd``` on its own will return you the the users home directory from whereever you are.

**Comment by winkleink** [comment]
You're right.  Multi-taking on a Windows Machine and got fuddles.

Meant cd ~

**Comment by SteveAmor** [comment]
You can just type ```cd``` you don't need the ```~``` :-)

**Comment by winkleink** [comment]
Learning all the time.

**Comment by martinohanlon** [comment]
Thanks for your contribution, I am making some changes to this project and am going to introduce the `~`.

**Pull request closed without merging**
